---
title: "SBIR 產業結構分析"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: default
    css: JH.css
    social: menu
    source_code: embed 
    logo: picture/mirdc48.png
    favicon:  picture/mirdc48.png
runtime: shiny
---

```{r}
pacman::p_load(shiny,shinyWidgets,shinythemes,flexdashboard)
pacman::p_load(dplyr,igraph,visNetwork,reshape2,stringr,DT,RColorBrewer)
pals18 = c(brewer.pal(12,"Set3"), brewer.pal(8,"Set1"), brewer.pal(8,"Set2"))
load("data/SBIR_analysis_data.RData")

#colnames(E)[c(1,7)] <- c("name","sub_class")
#E$tooltip = E$entity
#colnames(X) <- c("artUrl", "title", "date", "artSubject", "artSource", "tx")

S$doc_id= S$doc_id %>% as.numeric() #修正用
class_list=c("一般術語","國家地區","學研單位","政府單位","核心關鍵字","民間公司")
```

詳細設定 {data-icon="fa-cogs"}
=====================================================

Row {data-height=70%}
-----------------------------------------------------
### {data-width=25%}
```{r}
ctag = c('<font color="green"><b>', '<font color="red"><b>')
chooseSliderSkin("Modern")

# tags$style(type = 'text/css', css)

h6("
以公司在文章段落之中共同出現的頻率建立社會網絡，
利用共同鍵結將相關的公司拉在一起，
以社群偵測的方式分群並標示顏色，
藉以發現產業的結構。")

prettyRadioButtons(
  "Unit", "段落", choices = list("句"=1, "篇"=2),
  selected = 1, inline=T, icon=icon("check"), 
  status="success", animation="jelly")

prettyRadioButtons(
  "Cor", "關係", 
  choices = list("共同出現次數"=0, "相關係數"=1),
  selected = 1, inline=T, icon=icon("check"), 
  status="success", animation="jelly")
h6("如果字詞出現頻率較高，可以選擇'相關係數'來定義連結強度；如果字詞出現頻率較低，可以選擇'共同出現次數'作為連結強度")

sliderInput("Q1", "依出現頻率(%)篩選節點", 0, 1, 0.5, 0.01)
sliderInput("Q2", "依關聯強度(%)篩選鏈結", 0, 1, 0.08, 0.01)

prettyRadioButtons(
  "Giant", "只顯示相連結點", 
  choices = list("否"=0, "是"=1),
  selected = 1, inline=T, icon=icon("check"), 
  status="success", animation="jelly")

SX = reactive({
  VN = input$VN
  if(is.null(VN)) return(NULL)
  if(length(VN$nodes) > 0) {
    k = VN$nodes[[1]] %>% as.integer
    v = XX$Sent[,k]
    }
  else if(length(VN$edges) > 0) {
    k = strsplit(VN$edges[[1]],"-")[[1]] %>% as.integer
    v = rowSums(XX$Sent[,k]) == 2
  }
  else return(NULL)

  df = S[v,] %>%
    setNames(c('nid','sid','sentence')) %>%
    left_join(cbind(nid = 1:nrow(X), X),by="nid") %>%
    arrange(desc(artDate)) %>% as.data.frame() %>% head(200)

  list(df=df, k=k, v=v)
  })

```

### {data-width=75%}
```{r}
vis_network = function() {
  #input = list(Unit="1", Cor="1", Q1=0, Q2=0.7, Giant="1")

  q = quantile(E$freq[E$class == "民間公司"], input$Q1, na.rm = TRUE)
  si = which(E$class == "民間公司" & E$freq >= q)
  u = as.integer(input$Unit)
  if(input$Cor=="1") {
    x = CR[[u]][si,si] 
  }else{
    x = CO[[u]][si,si]
  }

 tt = with(E, sprintf(
  "%s: %s: %s(%s,%d)",entity[si],tooltip[si],chinese[si],
  class[si], freq[si])) %>% str_replace(",NA,", ",")
  nodes = data.frame(
    id=si, title=tt, value=2*sqrt(E$freq[si]),  
    stringsAsFactors=F)

  
  
  colnames(x) = rownames(x) = si
  x[lower.tri(x,T)] = 0
  x = subset(melt(x), value > 0)
  links = subset(x, value >= quantile(value, input$Q2))
  names(links)[1:2] = c('from','to')
  links$value = sqrt(links$value)
  links$id = paste0(links$from, "-", links$to)

  g = graph_from_data_frame(d=links, vertices=nodes, directed=F)
  if(input$Giant == "1") g = decompose(g)[[1]]
  V(g)$group = cluster_fast_greedy(g)$membership
  GL = toVisNetworkData(g)
  GL$nodes$tooltip = GL$nodes$label = E$tooltip[as.integer(GL$nodes$id)]

  E_class = unique(E$class)
  JS1 = "function(vis) {Shiny.onInputChange('VN', vis);}"
  tmp_network = visNetwork(GL$nodes, GL$edges) %>%
    visPhysics("forceAtlas2Based") %>%
    visEdges(color=list(highlight='red', opacity=0.5)) %>%
    visNodes(shape="square") %>%
    visOptions(highlightNearest=T, selectedBy="tooltip") %>% 
    visEvents(selectNode=JS1, selectEdge=JS1, 
              deselectNode=JS1, deselectEdge=JS1) 
  

}


renderVisNetwork( vis_network() )
```


Row {data-height=30%}
-----------------------------------------------------
### {data-width=35%}


```{r}
RowSel = eventReactive( # to prevent race-around
  input$myTable_rows_selected, {input$myTable_rows_selected})

renderDataTable({
  if(class(SX()) == 'list') {
    i = RowSel()
    df = SX()$df[i,]
    k = SX()$k
    df$z = paste0('<b><i>',df$artTitle,': </i></b>',df$artContent)
    for(j in 1:length(k)) df$z = str_replace_all(
      df$z, regex(paste0('(',E$alias[k[j]],')'), ignore_case = E$ignore[k[j]]),
      paste0(ctag[j], '\\1</b></font>')
      )
    datatable(
      df[,'z',drop=F],escape=F,rownames=F,colnames=c('The Selected Article'),
      extensions=c('Scroller'),options=list(
        scrollY="350px",scrollX=F,paging=F,searching=F,ordering=F,info=F)
      ) %>% formatStyle(columns=0:2, fontSize = '90%')
    }
  })
```


### {data-width=65%}
```{r}
uiOutput("dynamic")
output$dynamic <- renderUI({ dataTableOutput("myTable") })
output$myTable <- renderDataTable({
  if(!is.null(SX())) {
    k = SX()$k; df = SX()$df[,c('artDate','sentence')]#, 'artUrl'
    df$z = df$sentence
    cname=sprintf('Recent Co-Occurrence (%d): ',nrow(df))
    for(i in 1:length(k)) {
      if(i > 1) cname = paste0(cname, " and ")
      cname = paste0(cname, ctag[i], E$entity[k[i]], '</b></font>')
      df$z = str_replace_all(
      df$z, regex(paste0('(',E$alias[k[i]],')'), ignore_case = E$ignore[k[i]]),
      paste0(ctag[i], '\\1</b></font>') )
    }
    #df$artDate=createLink(df$artDate, df$artUrl) # 新增按鈕df[,c('artDate','z')]'artDate',!duplicated(df[,c('z')])
    datatable(
      df[,c('artDate','z')],escape=F,rownames=F,
      colnames=c('Date', cname),
      extensions=c('Scroller','Select'),
      selection=list(mode='single', selected=c(1), target='row'),
      options=list(
      scrollY="350px",scrollX=F,paging=F,searching=F,ordering=F,
      select = list(style='single'),info=F
      )) %>%
      formatStyle(columns=0:2, fontSize = '90%')
    } })
```




社會網路圖 {data-icon="fa-share-alt"}
=====================================================
```{r}
renderVisNetwork( vis_network() )
```
